### PR TITLE
Add `pac solution list --json`

### PR DESCRIPTION
**Pull request by richardcarrigan**
Adds previously undocumented `--json` optional parameter to the documentation for `pac solution list`.

### CODE REVIEW

**Comment by JimDaly** [comment]
@richardcarrigan 
This content is generated based the help content from pac cli product code.
We don't edit it by hand or accept contributions because they would be overwritten when the content is generated next time.

You are saying that pac solution list has a --json parameter that isn't documented.
I don't see it in the help. How do you know it exists?

```
C:\Users\me>pac solution list help
Microsoft PowerPlatform CLI
Version: 1.24.3+g95fc6ea

Help:
List all Solutions from the current Dataverse Organization

Commands:
Usage: pac solution list [--environment] [--environment-id]

  --environment               The target Environment ID or URL.  Default value is the environment of your currently active Dataverse Auth Profile. (alias: -env)
  --environment-id            (deprecated) The target Environment ID.  Default value is the environment of your currently active Dataverse Auth Profile.

```

**Comment by rajyraman** [comment]
@JimDaly - https://github.com/microsoft/powerplatform-vscode/discussions/323

**Comment by JimDaly** [comment]
@richardcarrigan 
Turns out you are correct. The following commands support `--json` and I understand that it returns the output of the command as a JSON-formatted string.
- `admin copy`
- `admin create`
- `admin list`
- `admin reset`
- `admin restore`
- `catalog list`
- `org who`
- `connector list`
- `solution list`

I'm working with the team to get information about this added to the docs, but we can't accept your pull request.
These notes will be added as **Remarks** for each command until the help system includes them too.

Thanks for raising this.

Jim

**Comment by richardcarrigan** [comment]
> @richardcarrigan This content is generated based the help content from pac cli product code. We don't edit it by hand or accept contributions because they would be overwritten when the content is generated next time.
> 
> You are saying that pac solution list has a --json parameter that isn't documented. I don't see it in the help. How do you know it exists?
> 
> ```
> C:\Users\me>pac solution list help
> Microsoft PowerPlatform CLI
> Version: 1.24.3+g95fc6ea
> 
> Help:
> List all Solutions from the current Dataverse Organization
> 
> Commands:
> Usage: pac solution list [--environment] [--environment-id]
> 
>   --environment               The target Environment ID or URL.  Default value is the environment of your currently active Dataverse Auth Profile. (alias: -env)
>   --environment-id            (deprecated) The target Environment ID.  Default value is the environment of your currently active Dataverse Auth Profile.
> ```

Completely understood. I was told about this parameter by the Power Platform Dev Tools team directly, and they did inform me that this content is auto-generated after submitting the PR.

**Pull request closed without merging**
