### PR TITLE
Update ALM for Power Platform GitHub Actions tutorial

### PR DESCRIPTION
**Pull request by paulbreuler**

### CODE REVIEW

**Comment by paulbreuler** [comment]
Work pending on the deployment module. Current modules are ready to review though.

**Comment by paulbreuler** [comment]
tag: @kkanakas, @marcelbf, @phecke

**Review by phecke — APPROVED** [review]
Your name appears in spn-secret-setup.gif

**Comment by paulbreuler** [comment]
> Your name appears in spn-secret-setup.gif

Good catch, I tried to remove all instance. I can update it really quick.

**Review by kkanakas — APPROVED** [review]
Thanks for making these changes.

**Pull request merged**
