### PR TITLE
Update roles with info about collaboration model

### PR DESCRIPTION
**Pull request by RobStand**
I added a link to "Collaborating and co-developing best practices" to promote that content in the CoE toolkit.

### CODE REVIEW

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[53bb72b](https://github.com/RobStand/power-platform/commits/53bb72b1e80500f0562026fa92d21e1f75d75c82)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0f829011)

<a id="0f829011"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209071801066083-1450/BuildReport?accessString=4c5457018945bb27f7d3fdc10f03eba8588a44b86a77aa6e9248f38f0c7abfb5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[821d8c0](https://github.com/RobStand/power-platform/commits/821d8c081e0ed529d05cce21d98005d151996863)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-91cc3cf5)

<a id="91cc3cf5"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209071822212446-1450/BuildReport?accessString=d1a564345ca4594b65464f6205363d25ebe8ce4064d5fd0935985a34685082b7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[170de0b](https://github.com/RobStand/power-platform/commits/170de0bff2ab94126500bcfc50239e9cc30bdcc4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6e17ec43)

<a id="6e17ec43"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209071833502454-1450/BuildReport?accessString=feed6c70c897a4801d6e42e498ce6ef5669d7d5c857eeb359f1acab38b24d5b4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[f8fd862](https://github.com/RobStand/power-platform/commits/f8fd86285f9b1fadbfe1a97d95e475f7d144000c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/online-requirements.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/admin/online-requirements.md) | :warning:Warning | | [Details](#user-content-d996048dbff087797f0565e3b6c2519f-9db855f4)
[power-platform/power-fx/reference/function-astype-istype.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/power-fx/reference/function-astype-istype.md) | :warning:Warning | | [Details](#user-content-2753c020774f17c81174047b7dc903a2-9db855f4)
[power-platform/power-fx/reference/function-colors.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/power-fx/reference/function-colors.md) | :warning:Warning | | [Details](#user-content-296e4a18d24f55511d08cda46a32b3fb-9db855f4)
[power-platform/power-fx/reference/function-json.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/power-fx/reference/function-json.md) | :warning:Warning | | [Details](#user-content-a3d85030f89cb0e90c1b0d1e411f315f-9db855f4)
[power-platform/guidance/adoption/roles.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/guidance/adoption/roles.md) | :white_check_mark:Succeeded | |

<a id="d996048dbff087797f0565e3b6c2519f-9db855f4"></a>
### [power-platform/admin/online-requirements.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/admin/online-requirements.md)
 - **Line 61, Column 3**: **[Warning: insecure-link - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://crl.microsoft.com/pki/crl/products/microsoftrootcert.crl' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="2753c020774f17c81174047b7dc903a2-9db855f4"></a>
### [power-platform/power-fx/reference/function-astype-istype.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/power-fx/reference/function-astype-istype.md)
 - **Line 109, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 111, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 115, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 119, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 131, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="296e4a18d24f55511d08cda46a32b3fb-9db855f4"></a>
### [power-platform/power-fx/reference/function-colors.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/power-fx/reference/function-colors.md)
 - **Line 43, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 47, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="a3d85030f89cb0e90c1b0d1e411f315f-9db855f4"></a>
### [power-platform/power-fx/reference/function-json.md](https://github.com/RobStand/power-platform/blob/patch-1/power-platform/power-fx/reference/function-json.md)
 - **Line 93, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 97, Column 4**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209072052089936-1450/BuildReport?accessString=b835491c58087e41b6ffe257c0118bc0d4bdae2b78e97aa204bd9b8270b34d39).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by manuelap-msft — APPROVED** [review]

**Review by manuelap-msft — APPROVED** [review]

**Pull request merged**
