### PR TITLE
Update cross-tenant-restrictions.md

### PR DESCRIPTION
**Pull request by mihaelablendea**
Adding known issue

### CODE REVIEW

**Comment by buck1ey** [comment]
Learn Build status updates of commit _[fa6ced3](https://github.com/mihaelablendea/power-platform/commits/fa6ced39b7c017b28dadfefe31dda726143462bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/cross-tenant-restrictions.md](https://github.com/mihaelablendea/power-platform/blob/patch-1/power-platform/admin/cross-tenant-restrictions.md) | :warning:Warning | | [Details](#user-content-cc2d951ad1d58b5ca694c8f813aff35f-93bf582f)

<a id="cc2d951ad1d58b5ca694c8f813aff35f-93bf582f"></a>
### [power-platform/admin/cross-tenant-restrictions.md](https://github.com/mihaelablendea/power-platform/blob/patch-1/power-platform/admin/cross-tenant-restrictions.md)
 - **Line 39, Column 49**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../connectors/connector-reference.md'.`````
 - **Line 165, Column 4**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../connectors/connector-reference.md'.`````
 - **Line 165, Column 385**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../wp-data-loss-prevention'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202211152314181741-1600/BuildReport?accessString=edd38d508aad5eabc28a17eb361c0da52e0a8f7d7b5f0bf17418e0f700546775).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by buck1ey** [comment]
Learn Build status updates of commit _[0706993](https://github.com/mihaelablendea/power-platform/commits/0706993c5d03ace5130187ba024543b3dbbec3bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/cross-tenant-restrictions.md](https://github.com/mihaelablendea/power-platform/blob/patch-1/power-platform/admin/cross-tenant-restrictions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202211152330582859-1600/BuildReport?accessString=e02acde51e300c110a106222096b763b416aed858cccce3ddcd11c366d333e98).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by mihaelablendea** [comment]
#signoff please merge

**Comment by buck1ey** [comment]
Learn Build status updates of commit _[8841f50](https://github.com/mihaelablendea/power-platform/commits/8841f507c69df66e879f32a97b161a26c57206c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/cross-tenant-restrictions.md](https://github.com/mihaelablendea/power-platform/blob/patch-1/power-platform/admin/cross-tenant-restrictions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202211161715173719-1600/BuildReport?accessString=1ea17aa286ade1dd4f89cd68f20d7745b1819b639b99c5a68200e734a67fe693).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Pull request merged**
