### PR TITLE
removed duplicate setting powerPlatform.powerApps.disableConnectionSharingWithEveryone in list-tenantsettings.md

### PR DESCRIPTION
**Pull request by m-hanisch**
duplicate in settings:
- powerPlatform.powerApps.DisableConnectionSharingWithEveryone (line 115)
- powerPlatform.powerApps.disableConnectionSharingWithEveryone (line 122)

### CODE REVIEW

**Comment by m-hanisch** [comment]
@sericks007 
there is a duplicate setting file list-tenantsettings.md

powerPlatform.powerApps.DisableConnectionSharingWithEveryone (line 115)
powerPlatform.powerApps.disableConnectionSharingWithEveryone (line 122)

My commit was blocked. May you verify and proceed? thx in advance.

**Review by sericks007 — APPROVED** [review]

**Comment by m-hanisch** [comment]
@sericks007 
FYI:
same applies for setting - also duplicate
powerPlatform.teamsIntegration.shareWithColleaguesUserLimit

**Comment by sericks007** [comment]
@m-hanisch, which one should be removed -- the first or second instance?

**Comment by m-hanisch** [comment]
@sericks007 
In this case both settings (rows / lines) are totally identical.
powerPlatform.teamsIntegration.shareWithColleaguesUserLimit

In my opinoi, remove the first instance (line 114), because the other settings majorily are sorted by setting property name and therefore `powerPlatform.teamsIntegration.shareWithColleaguesUserLimit` does not fit in the group of `powerPlatform.powerApps.<xyz>`

**Comment by sericks007** [comment]
@m-hanisch, OK, will do!  Thank you!

**Pull request merged**
