### PR TITLE
Update add-ons.md

### PR DESCRIPTION
**Pull request by PriyaKodukula**

### CODE REVIEW

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[a44f36f](https://github.com/PriyaKodukula/power-platform/commits/a44f36f99dc3b9f27481cc4ab533b4e55156e910)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7750e7fc)

<a id="7750e7fc"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209192006116121-1467/BuildReport?accessString=7a00d66ccba9af776cdb375324127913085798bbd8897e60493108e1531f1b69).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[5fb16a6](https://github.com/PriyaKodukula/power-platform/commits/5fb16a6153dc5369ead58e0f24df62668e3c5ebe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9bcae15e)

<a id="9bcae15e"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209200225236235-1467/BuildReport?accessString=b6780ae8d506e22c53caf004a25af6161232cb80bf61a57a3042d30f9e919b6b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by MSFTMan — APPROVED** [review]

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[5fb16a6](https://github.com/PriyaKodukula/power-platform/commits/5fb16a6153dc5369ead58e0f24df62668e3c5ebe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/power-automate-licensing/add-ons.md](https://github.com/PriyaKodukula/power-platform/blob/patch-3/power-platform/admin/power-automate-licensing/add-ons.md) | :warning:Warning | | [Details](#user-content-0faeb0d64dcc864645e1807fc0bb6bed-5c766d88)

<a id="0faeb0d64dcc864645e1807fc0bb6bed-5c766d88"></a>
### [power-platform/admin/power-automate-licensing/add-ons.md](https://github.com/PriyaKodukula/power-platform/blob/patch-3/power-platform/admin/power-automate-licensing/add-ons.md)
 - **Line 28, Column 94**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#transition-period' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209201918463215-1467/BuildReport?accessString=14b126c613182aa787804d1ef2c0c7fbe4b19ec48f1761ce032ad24531fbcb1c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[f2a9c56](https://github.com/PriyaKodukula/power-platform/commits/f2a9c563a35079a067d140450f6337b9051ac6fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/power-automate-licensing/add-ons.md](https://github.com/PriyaKodukula/power-platform/blob/patch-3/power-platform/admin/power-automate-licensing/add-ons.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202209202001257831-1467/BuildReport?accessString=589db51fb6c702ac47dc5d943c87adbb80deee59216d8af00b6388bfd1e514e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
