### PR TITLE
Minor Fixes (links, cmdlet names)

### PR DESCRIPTION
**Pull request by modery**
1) Correcting a cmdlet name (to use the newer name)
2) Fixing a few broken links

### CODE REVIEW

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[0665245](https://github.com/modery/power-platform/commits/0665245bffa8eec62a11cf3c30c41a3f753bbece)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/powerapps-gdpr-delete-dsr.md](https://github.com/modery/power-platform/blob/main/power-platform/admin/powerapps-gdpr-delete-dsr.md) | :bulb:Suggestion | | [Details](#user-content-0ba016aced34d875c2d900ff9a6c0f50-7db651e8)
[power-platform/guidance/coe/after-setup.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/after-setup.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/almaccelerator-app-registrations.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/almaccelerator-app-registrations.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup-archive-components.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup-archive-components.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup-core-components.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup-quarantine-components.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup-quarantine-components.md) | :white_check_mark:Succeeded | |

<a id="0ba016aced34d875c2d900ff9a6c0f50-7db651e8"></a>
### [power-platform/admin/powerapps-gdpr-delete-dsr.md](https://github.com/modery/power-platform/blob/main/power-platform/admin/powerapps-gdpr-delete-dsr.md)
 - **Line 95, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide`````
 - **Line 167, Column 19**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide`````
 - **Line 215, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202208100334520686-1394/BuildReport?accessString=93648f8c06b0d7c0b26a79634e6e1d56d86ff5eb73d3ea7b7a301b9d42c29732).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jimholtz** [comment]
Revising the following now:
power-platform/admin/powerapps-gdpr-delete-dsr.md

**Comment by manuelap-msft** [comment]
I have reviewed the changes proposed to the files in the /coe folder and they look good to me. I'm not sure if I can approve this PR as it contains files that I don't look after (gdpr file).

**Comment by buck1ey** [comment]
Docs Build status updates of commit _[46a6ee0](https://github.com/modery/power-platform/commits/46a6ee0d793db40c6aac69edda8488642660d152)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[power-platform/admin/powerapps-gdpr-delete-dsr.md](https://github.com/modery/power-platform/blob/main/power-platform/admin/powerapps-gdpr-delete-dsr.md) | :bulb:Suggestion | | [Details](#user-content-0ba016aced34d875c2d900ff9a6c0f50-cc4a044f)
[power-platform/guidance/coe/after-setup.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/after-setup.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/almaccelerator-app-registrations.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/almaccelerator-app-registrations.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup-archive-components.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup-archive-components.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup-core-components.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md) | :white_check_mark:Succeeded | |
[power-platform/guidance/coe/setup-quarantine-components.md](https://github.com/modery/power-platform/blob/main/power-platform/guidance/coe/setup-quarantine-components.md) | :white_check_mark:Succeeded | |

<a id="0ba016aced34d875c2d900ff9a6c0f50-cc4a044f"></a>
### [power-platform/admin/powerapps-gdpr-delete-dsr.md](https://github.com/modery/power-platform/blob/main/power-platform/admin/powerapps-gdpr-delete-dsr.md)
 - **Line 95, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide`````
 - **Line 167, Column 19**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide`````
 - **Line 215, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/81735916-f7c3-feae-a32e-d5a2e0c4f5f6/202208222334362716-1394/BuildReport?accessString=937bd2c510186ba32c545c31a7b3158484dcc9cd933c4f8e779ef43f6206ad5f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/81735916-f7c3-feae-a32e-d5a2e0c4f5f6?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
